### ISSUE TITLE
Backup failed because: Unable to write file at location:

### ISSUE THREAD

**Issue by RichardDight** [masbug/flysystem-google-drive-ext#103]
I'm trying to integrate laravel backups with a google team drive. I'm able to successfully create back ups locally on google drive folders I've created. However whenever I try to add a google drive team id, I keep running into this error whenever `GoogleDriveAdapter->writeData` is ran:

```
Starting backup...
Dumping database mydb...
Determining files to backup...
Zipping 1 files and directories...
Created zip containing 1 files and directories. Size is 14.28 MB
Copying zip to disk named google...
Copying zip failed because: Unable to write file at location: local-backup-2023-03-06-14-50-06.zip. Not able to write the file.
Backup failed because Unable to write file at location: local-backup-2023-03-06-14-07-05.zip. Not able to write the file.
#0 /var/www/html/vendor/masbug/flysystem-google-drive-ext/src/GoogleDriveAdapter.php(440): League\Flysystem\UnableToWriteFile::atLocation('local-backup-20...', 'Not able to wri...')
#1 /var/www/html/vendor/masbug/flysystem-google-drive-ext/src/GoogleDriveAdapter.php(457): Masbug\Flysystem\GoogleDriveAdapter->writeData('local-backup-20...', Resource id #1138, Object(League\Flysystem\Config))
#2 /var/www/html/vendor/league/flysystem/src/Filesystem.php(66): Masbug\Flysystem\GoogleDriveAdapter->writeStream('local-backup-20...', Resource id #1138, Object(League\Flysystem\Config))
#3 /var/www/html/vendor/spatie/laravel-backup/src/BackupDestination/BackupDestination.php(84): League\Flysystem\Filesystem->writeStream('/local-backup-2...', Resource id #1138, Array)
#4 /var/www/html/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(292): Spatie\Backup\BackupDestination\BackupDestination->write('/var/www/html/s...')
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(235): Spatie\Backup\Tasks\Backup\BackupJob->Spatie\Backup\Tasks\Backup\{closure}(Object(Spatie\Backup\BackupDestination\BackupDestination), 0)
#6 /var/www/html/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(284): Illuminate\Support\Collection->each(Object(Closure))
#7 /var/www/html/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(168): Spatie\Backup\Tasks\Backup\BackupJob->copyToBackupDestinations('/var/www/html/s...')
#8 /var/www/html/vendor/spatie/laravel-backup/src/Commands/BackupCommand.php(58): Spatie\Backup\Tasks\Backup\BackupJob->run()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Spatie\Backup\Commands\BackupCommand->handle()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(661): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\Container\Container->call(Array)
#15 /var/www/html/vendor/symfony/console/Command/Command.php(312): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(152): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#17 /var/www/html/vendor/spatie/laravel-backup/src/Commands/BaseCommand.php(28): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /var/www/html/vendor/symfony/console/Application.php(1022): Spatie\Backup\Commands\BaseCommand->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /var/www/html/vendor/symfony/console/Application.php(314): Symfony\Component\Console\Application->doRunCommand(Object(Spatie\Backup\Commands\BackupCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /var/www/html/vendor/symfony/console/Application.php(168): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php(102): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(155): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /var/www/html/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 {main}
Backup failed because: Unable to write file at location: local-backup-2023-03-06-14-07-05.zip. Not able to write the file.

```

Suspected it might be a permissions issue. But my permissions seem fine. The zip folder is created in the shared drive, but seems to be unfinished.

**Comment by parallels999** [comment]
Did you follow all implementation steps ??

Here a tutorial: [laravel-google-drive-ext-demo](https://github.com/erikn69/laravel-google-drive-ext-demo)

**Comment by RichardDight** [comment]
Yes I've followed the steps:

1. Added a google drive storage provider
2. Added drive credentials to .env
3. Added custom adapter & added a custom service provider
4. registered a google file system disk

Everything is working fine when I'm not using `GOOGLE_DRIVE_TEAM_DRIVE_ID` . And as stated, the zip with the sql file is created and then this error occurs ^

Drive SDK permissions within the google organisation is also set to 'ON'

**Comment by parallels999** [comment]
what are you setting in folder? wich options are you setting?
Show some code, wich versions are you using?
i'm just guessing
Also manually copying files to google disk works?

**Comment by RichardDight** [comment]
The only option I'm setting is the teamDriveId.

`array:1 [▼
  "teamDriveId" => "0YBee_YovmGFHUk9ANC"
]`

I can see the drive listed `$googleDisk->getAdapter()->getService()->teamdrives->listTeamdrives()->getTeamDrives()` here.

Define manually?
I can successfully `Storage::cloud()->put()` with a new file or an existing image to the team drive successfully

**Comment by RichardDight** [comment]
This is the function that's throwing the exception:
```
    protected function copyToBackupDestinations(string $path): void
    {
        $this->backupDestinations
            ->each(function (BackupDestination $backupDestination) use ($path) {
                try {
                    if (! $backupDestination->isReachable()) {
                        throw new Exception("Could not connect to disk {$backupDestination->diskName()} because: {$backupDestination->connectionError()}");
                    }

                    consoleOutput()->info("Copying zip to disk named {$backupDestination->diskName()}...");
                    
                    $backupDestination->write($path);

                    consoleOutput()->info("Successfully copied zip to disk named {$backupDestination->diskName()}.");

                    $this->sendNotification(new BackupWasSuccessful($backupDestination));
                } catch (Exception $exception) {
                    consoleOutput()->error("Copying zip failed because: {$exception->getMessage()}.");

                    $this->sendNotification(new BackupHasFailed($exception, $backupDestination));

                    throw $exception;
                }
            });

```
Here is the backup destination I'm using:

```
Spatie\Backup\BackupDestination\BackupDestination {#1678 ▼

  #disk: Illuminate\Filesystem\FilesystemAdapter {#1676 ▼
  
    #driver: League\Flysystem\Filesystem {#1673 ▼
    
      -config: League\Flysystem\Config {#1674 ▼
        -options: []
      }
      -pathNormalizer: League\Flysystem\WhitespacePathNormalizer {#1675}
      -adapter: Masbug\Flysystem\GoogleDriveAdapter {[#1671 ▼]
      (https://github.com/masbug/flysystem-google-drive-ext/issues/103#sf-dump-1940293931-ref21671)
        #service: Google\Service\Drive {#1653 ▶}
        
        #spaces: "drive"
        #root: "0YBee_YovmGFHUk9ANC"
        #publishPermission: array:3 [▶]
        
        -cacheFileObjects: array:6 [▶]
        
        -cacheHasDirs: array:1 [▶]
        
        -useHasDir: false
        -usePermanentDelete: false
        -useSinglePathTransaction: false
        
        -options: array:12 [▼
          "spaces" => "drive"
          "useHasDir" => false
          "useDisplayPaths" => true
          "usePermanentDelete" => false
          "useSinglePathTransaction" => false
          "publishPermission" => array:3 [▶]
          "appsExportMap" => array:6 [▶]
          "parameters" => []
          "driveId" => null
          "sanitize_chars" => array:57 [▶]
          "sanitize_replacement_char" => "_"
          "teamDriveId" => "0AAle_YovmDGHUk9PVA"
        ]
        -useDisplayPaths: true
        -rootId: null
        -cachedPaths: []
        -requestedIds: []
        -optParams: array:9 [▶]
        -prefixer: League\Flysystem\PathPrefixer {#1672 ▶}
      }
      -publicUrlGenerator: null
      -temporaryUrlGenerator: null
    }
    #adapter: Masbug\Flysystem\GoogleDriveAdapter {[#1671 ▶](https://github.com/masbug/flysystem-google-drive-ext/issues/103#sf-dump-1940293931-ref21671)}
    #config: []
    #prefixer: League\Flysystem\PathPrefixer {#1677 ▶}
    #temporaryUrlCallback: null
  }
  #diskName: "google"
  #backupName: ""
  +connectionError: null
  #backupCollectionCache: null
}
```

**Comment by parallels999** [comment]
> I can successfully Storage::cloud()->put() with a new file or an existing image to the team drive successfully

Weird, i am using spatie/laravel-backup without problems
"teamDriveId" is already deprecated, it was changed to "driveId" wich here is null
https://github.com/masbug/flysystem-google-drive-ext/blob/3947d39be212bff9cea95b2a5252e52c9eb36cc0/src/GoogleDriveAdapter.php#L2211

On folder did you set `/` or `null`

**Comment by RichardDight** [comment]
> > I can successfully Storage::cloud()->put() with a new file or an existing image to the team drive successfully
> 
> Weird, i am using spatie/laravel-backup without problems "teamDriveId" is already deprecated, it was changed to "driveId" wich here is null
> 
> https://github.com/masbug/flysystem-google-drive-ext/blob/3947d39be212bff9cea95b2a5252e52c9eb36cc0/src/GoogleDriveAdapter.php#L2211
> 
> On folder did you set `/` or `null`

Hmm, you're right. Seems like the code for `teamDriveId` still exists though for now, no?
I see in the demo you linked, in the service provider that ` $options['teamdriveId'] = $config['teamDriveId'];` is also being passed there.

When I change this to `driveId` the backup no longer targets the team directory, and goes straight into my root directory.

my folder is currently null, however I pass '/' `$config['folder'] ?? '/'` like so

**Comment by parallels999** [comment]
So, it is fixed now?? I don't have more ideas, try to do a debug

**Comment by parallels999** [comment]
Maybe this https://github.com/masbug/flysystem-google-drive-ext/issues/57

**Comment by RichardDight** [comment]
Debugging atm. Still not fixed. Have no issues with what was mentioned in #57

**Comment by RichardDight** [comment]
Fixed the issue.

So replacing the `option['teamDriveId']` with `option['driveId']` yesterday didn't work. I added an additional option just now having both `'teamDriveId'` and also `'driveId'` and that solved the issue.

```
                if (isset($config['teamDriveId'])) {
                    $options['teamDriveId'] = $config['teamDriveId'];
                    $options['driveId'] = $config['teamDriveId'];
                }
```

Thanks for assisting, I appreciate it
